/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright 2025-2026 Estado de Goiás (SES-GO) e Universidade Federal de Goiás (UFG).
 */

package br.gov.go.saude.fhir.safira.engine.domain.fhir;

import lombok.Getter;

/**
 * CodeSystem FHIR {@code situacao-excepcional-assinatura}, versão 0.1.2.
 *
 * <p>Cada constante mapeia um código do CodeSystem publicado em
 * {@code https://fhir.saude.go.gov.br/r4/seguranca/CodeSystem/situacao-excepcional-assinatura}
 * com sua severidade padrão e grupo hierárquico.
 */
@Getter
public enum SignatureExceptionCode {
    POLICY("POLICY", "Problemas com Política de Assinatura", null, "POLICY"),
    POLICY_MISSING("POLICY.MISSING", "Política de Assinatura Ausente", "error", "POLICY"),
    POLICY_URI_INVALID("POLICY.URI-INVALID", "URI da Política Inválida", "error", "POLICY"),
    POLICY_VERSION_UNSUPPORTED("POLICY.VERSION-UNSUPPORTED", "Versão da Política Não Suportada", "error", "POLICY"),
    POLICY_VERSION_DEPRECATED("POLICY.VERSION-DEPRECATED", "Versão da Política Descontinuada", "warning", "POLICY"),
    CERT("CERT", "Problemas com Certificados Digitais", null, "CERT"),
    CERT_INVALID_FORMAT("CERT.INVALID-FORMAT", "Formato de Certificado Inválido", "error", "CERT"),
    CERT_CHAIN_VALIDATION_FAILED("CERT.CHAIN-VALIDATION-FAILED", "Validação da Cadeia de Certificados Falhou", "error", "CERT"),
    CERT_EXPIRED("CERT.EXPIRED", "Certificado Expirado", "error", "CERT"),
    CERT_NOT_YET_VALID("CERT.NOT-YET-VALID", "Certificado Ainda Não Válido", "error", "CERT"),
    CERT_REVOKED("CERT.REVOKED", "Certificado Revogado", "error", "CERT"),
    CERT_ISSUE_DATE_TOO_OLD("CERT.ISSUE-DATE-TOO-OLD", "Data de Emissão Anterior ao Mínimo Exigido", "error", "CERT"),
    CERT_NOT_ICP_BRASIL("CERT.NOT-ICP-BRASIL", "Certificado Não é ICP-Brasil", "error", "CERT"),
    CERT_NOT_TRUSTED_ROOT("CERT.NOT-TRUSTED-ROOT", "Raiz Não Confiável ICP-Brasil", "error", "CERT"),
    CERT_NEAR_EXPIRY("CERT.NEAR-EXPIRY", "Certificado Próximo ao Vencimento", "warning", "CERT"),
    CERT_WEAK_KEY("CERT.WEAK-KEY", "Chave Criptográfica Fraca", "error", "CERT"),
    CERT_UNSUPPORTED_ALGORITHM("CERT.UNSUPPORTED-ALGORITHM", "Algoritmo Não Suportado", "error", "CERT"),
    CERT_CHAIN_INCOMPLETE("CERT.CHAIN-INCOMPLETE", "Cadeia Incompleta", "error", "CERT"),
    CERT_MISSING_IDENTIFICATION("CERT.MISSING-IDENTIFICATION", "Identificação Ausente no Certificado", "error", "CERT"),
    REVOCATION("REVOCATION", "Problemas com Validação de Revogação", null, "REVOCATION"),
    REVOCATION_OCSP_UNAVAILABLE("REVOCATION.OCSP-UNAVAILABLE", "Serviço OCSP Indisponível", "error", "REVOCATION"),
    REVOCATION_CRL_UNAVAILABLE("REVOCATION.CRL-UNAVAILABLE", "Lista CRL Indisponível", "error", "REVOCATION"),
    REVOCATION_CRL_INVALID("REVOCATION.CRL-INVALID", "CRL Inválida", "error", "REVOCATION"),
    REVOCATION_OCSP_INVALID("REVOCATION.OCSP-INVALID", "OCSP Inválido", "error", "REVOCATION"),
    REVOCATION_NO_CONNECTIVITY("REVOCATION.NO-CONNECTIVITY", "Sem Conectividade Externa", "error", "REVOCATION"),
    REVOCATION_CACHE_EXPIRED("REVOCATION.CACHE-EXPIRED", "Cache de Revogação Expirado", "warning", "REVOCATION"),
    REVOCATION_NO_DISTRIBUTION_POINTS("REVOCATION.NO-DISTRIBUTION-POINTS", "Pontos de Distribuição Ausentes", "error", "REVOCATION"),
    REVOCATION_RESPONSE_MALFORMED("REVOCATION.RESPONSE-MALFORMED", "Resposta de Revogação Malformada", "error", "REVOCATION"),
    CRYPTO("CRYPTO", "Problemas Criptográficos", null, "CRYPTO"),
    CRYPTO_ALGORITHM_UNSUPPORTED("CRYPTO.ALGORITHM-UNSUPPORTED", "Algoritmo Não Suportado", "error", "CRYPTO"),
    CRYPTO_SIGNATURE_CREATION_FAILED("CRYPTO.SIGNATURE-CREATION-FAILED", "Falha na Criação de Assinatura", "fatal", "CRYPTO"),
    CRYPTO_SIGNATURE_VALIDATION_FAILED("CRYPTO.SIGNATURE-VALIDATION-FAILED", "Falha na Validação de Assinatura", "error", "CRYPTO"),
    CRYPTO_KEY_INACCESSIBLE("CRYPTO.KEY-INACCESSIBLE", "Chave Inacessível", "error", "CRYPTO"),
    CRYPTO_DEVICE_BLOCKED("CRYPTO.DEVICE-BLOCKED", "Dispositivo Bloqueado", "error", "CRYPTO"),
    CRYPTO_HASH_VERIFICATION_FAILED("CRYPTO.HASH-VERIFICATION-FAILED", "Verificação de Hash Falhou", "error", "CRYPTO"),
    CRYPTO_ENTROPY_INSUFFICIENT("CRYPTO.ENTROPY-INSUFFICIENT", "Entropia Insuficiente", "fatal", "CRYPTO"),
    CRYPTO_TIMING_ATTACK_DETECTED("CRYPTO.TIMING-ATTACK-DETECTED", "Possível Ataque de Temporização Detectado", "warning", "CRYPTO"),
    CRYPTO_INVALID_PUBLIC_KEY("CRYPTO.INVALID-PUBLIC-KEY", "Chave Pública Inválida", "error", "CRYPTO"),
    CRYPTO_PIN_INVALID("CRYPTO.PIN-INVALID", "PIN Inválido", "error", "CRYPTO"),
    CRYPTO_WEAK_KEY("CRYPTO.WEAK-KEY", "Chave Fraca", "error", "CRYPTO"),
    FORMAT("FORMAT", "Problemas de Formato e Estrutura", null, "FORMAT"),
    FORMAT_BUNDLE_MALFORMED("FORMAT.BUNDLE-MALFORMED", "Bundle FHIR Malformado", "error", "FORMAT"),
    FORMAT_BUNDLE_EMPTY("FORMAT.BUNDLE-EMPTY", "Bundle Vazio", "error", "FORMAT"),
    FORMAT_PROVENANCE_INVALID("FORMAT.PROVENANCE-INVALID", "Provenance Inválido", "error", "FORMAT"),
    FORMAT_TARGET_REFERENCE_MISSING("FORMAT.TARGET-REFERENCE-MISSING", "Referência de Target Ausente", "error", "FORMAT"),
    FORMAT_JSON_MALFORMED("FORMAT.JSON-MALFORMED", "JSON Malformado", "error", "FORMAT"),
    FORMAT_BASE64_INVALID("FORMAT.BASE64-INVALID", "Base64 Inválido", "error", "FORMAT"),
    FORMAT_JWS_MALFORMED("FORMAT.JWS-MALFORMED", "JWS Malformado", "error", "FORMAT"),
    FORMAT_BUNDLE_RESOURCE_MISSING("FORMAT.BUNDLE-RESOURCE-MISSING", "Recurso do Bundle Ausente", "error", "FORMAT"),
    FORMAT_REFERENCE_INVALID("FORMAT.REFERENCE-INVALID", "Referência Inválida", "error", "FORMAT"),
    FORMAT_REFERENCE_MISSING("FORMAT.REFERENCE-MISSING", "Referência Não Encontrada", "error", "FORMAT"),
    FORMAT_CANONICALIZATION_FAILED("FORMAT.CANONICALIZATION-FAILED", "Falha na Canonicalização", "fatal", "FORMAT"),
    FORMAT_UUID_INVALID("FORMAT.UUID-INVALID", "UUID Inválido", "error", "FORMAT"),
    FORMAT_DUPLICATE_FULLURL("FORMAT.DUPLICATE-FULLURL", "fullUrl Duplicado", "error", "FORMAT"),
    FORMAT_DUPLICATE_TARGET_REFERENCE("FORMAT.DUPLICATE-TARGET-REFERENCE", "Referência Target Duplicada", "error", "FORMAT"),
    FORMAT_RESOURCE_TOO_LARGE("FORMAT.RESOURCE-TOO-LARGE", "Recurso Muito Grande", "error", "FORMAT"),
    FORMAT_TOO_MANY_ENTRIES("FORMAT.TOO-MANY-ENTRIES", "Muitas Entradas", "error", "FORMAT"),
    FORMAT_BUNDLE_ORDER_MISMATCH("FORMAT.BUNDLE-ORDER-MISMATCH", "Ordem do Bundle Incompatível", "error", "FORMAT"),
    FORMAT_NON_DETERMINISTIC_ORDER("FORMAT.NON-DETERMINISTIC-ORDER", "Ordem Não Determinística", "error", "FORMAT"),
    FORMAT_PROFILE_VALIDATION_FAILED("FORMAT.PROFILE-VALIDATION-FAILED", "Validação de Perfil Falhou", "error", "FORMAT"),
    FORMAT_EXTENSION_MISSING("FORMAT.EXTENSION-MISSING", "Extensão Obrigatória Ausente", "error", "FORMAT"),
    FORMAT_RESOURCE_INVALID("FORMAT.RESOURCE-INVALID", "Recurso Inválido", "error", "FORMAT"),
    FORMAT_INVALID_TIMESTAMP("FORMAT.INVALID-TIMESTAMP", "Timestamp Inválido", "error", "FORMAT"),
    FORMAT_PROVENANCE_TARGET_INVALID("FORMAT.PROVENANCE-TARGET-INVALID", "Referência de Target Inválida", "error", "FORMAT"),
    FORMAT_PROVENANCE_TARGET_DUPLICATE("FORMAT.PROVENANCE-TARGET-DUPLICATE", "Referência de Target Duplicada", "error", "FORMAT"),
    FORMAT_RESOURCE_TYPE_UNSUPPORTED("FORMAT.RESOURCE-TYPE-UNSUPPORTED", "Tipo de Resource Não Suportado", "error", "FORMAT"),
    FORMAT_SIGNATURE_MISSING("FORMAT.SIGNATURE-MISSING", "Assinatura Ausente", "error", "FORMAT"),
    FORMAT_JWK_INVALID("FORMAT.JWK-INVALID", "JWK Inválido", "error", "FORMAT"),
    FORMAT_CERT_PEM_INVALID("FORMAT.CERT-PEM-INVALID", "Certificado PEM Inválido", "error", "FORMAT"),
    DEVICE("DEVICE", "Problemas com Dispositivos Seguros", null, "DEVICE"),
    DEVICE_SMARTCARD_NOT_FOUND("DEVICE.SMARTCARD-NOT-FOUND", "Smartcard Não Encontrado", "error", "DEVICE"),
    DEVICE_TOKEN_NOT_FOUND("DEVICE.TOKEN-NOT-FOUND", "Token Não Encontrado", "error", "DEVICE"),
    DEVICE_PIN_BLOCKED("DEVICE.PIN-BLOCKED", "PIN Bloqueado", "error", "DEVICE"),
    DEVICE_MIDDLEWARE_ERROR("DEVICE.MIDDLEWARE-ERROR", "Erro no Middleware", "error", "DEVICE"),
    DEVICE_CERTIFICATE_NOT_FOUND("DEVICE.CERTIFICATE-NOT-FOUND", "Certificado Não Encontrado no Dispositivo", "error", "DEVICE"),
    DEVICE_KEY_ACCESS_DENIED("DEVICE.KEY-ACCESS-DENIED", "Acesso à Chave Negado", "error", "DEVICE"),
    MIDDLEWARE("MIDDLEWARE", "Problemas com Middleware Criptográfico", null, "MIDDLEWARE"),
    MIDDLEWARE_LIBRARY_NOT_FOUND("MIDDLEWARE.LIBRARY-NOT-FOUND", "Biblioteca de Middleware Não Encontrada", "error", "MIDDLEWARE"),
    MIDDLEWARE_INVALID_CONFIG("MIDDLEWARE.INVALID-CONFIG", "Configuração de Middleware Inválida", "error", "MIDDLEWARE"),
    MIDDLEWARE_LIBRARY_PATH_INVALID("MIDDLEWARE.LIBRARY-PATH-INVALID", "Caminho da Biblioteca Inválido", "error", "MIDDLEWARE"),
    MIDDLEWARE_LIBRARY_INVALID_FORMAT("MIDDLEWARE.LIBRARY-INVALID-FORMAT", "Formato de Biblioteca Inválido", "error", "MIDDLEWARE"),
    MIDDLEWARE_SLOT_ID_INVALID("MIDDLEWARE.SLOT-ID-INVALID", "Slot ID Inválido", "error", "MIDDLEWARE"),
    MIDDLEWARE_TOKEN_LABEL_INVALID("MIDDLEWARE.TOKEN-LABEL-INVALID", "Token Label Inválido", "error", "MIDDLEWARE"),
    MIDDLEWARE_UNSUPPORTED_MECHANISMS("MIDDLEWARE.UNSUPPORTED-MECHANISMS", "Mecanismos Não Suportados", "error", "MIDDLEWARE"),
    MIDDLEWARE_SESSION_MODE_INVALID("MIDDLEWARE.SESSION-MODE-INVALID", "Modo de Sessão Inválido", "error", "MIDDLEWARE"),
    MIDDLEWARE_TIMEOUT_OUT_OF_RANGE("MIDDLEWARE.TIMEOUT-OUT-OF-RANGE", "Timeout de Middleware Fora da Faixa", "error", "MIDDLEWARE"),
    MIDDLEWARE_AUTH_ATTEMPTS_OUT_OF_RANGE("MIDDLEWARE.AUTH-ATTEMPTS-OUT-OF-RANGE", "Tentativas de Autenticação Fora da Faixa", "error", "MIDDLEWARE"),
    MIDDLEWARE_RETRY_CONFIG_INVALID("MIDDLEWARE.RETRY-CONFIG-INVALID", "Configuração de Retry Inválida", "error", "MIDDLEWARE"),
    CONFIG("CONFIG", "Problemas de Configuração", null, "CONFIG"),
    CONFIG_INVALID_PARAMETER("CONFIG.INVALID-PARAMETER", "Parâmetro de Configuração Inválido", "error", "CONFIG"),
    CONFIG_INVALID_STRATEGY("CONFIG.INVALID-STRATEGY", "Estratégia de Timestamp Inválida", "error", "CONFIG"),
    CONFIG_TTL_OUT_OF_RANGE("CONFIG.TTL-OUT-OF-RANGE", "TTL de Cache Fora da Faixa", "error", "CONFIG"),
    CONFIG_TIMEOUT_OUT_OF_RANGE("CONFIG.TIMEOUT-OUT-OF-RANGE", "Timeout Fora da Faixa", "error", "CONFIG"),
    CONFIG_TIMESTAMP_OUT_OF_RANGE("CONFIG.TIMESTAMP-OUT-OF-RANGE", "Timestamp de Referência Fora da Faixa", "error", "CONFIG"),
    CONFIG_TSA_AUTH_FAILED("CONFIG.TSA-AUTH-FAILED", "Falha na Autenticação TSA", "error", "CONFIG"),
    CONFIG_TSA_URL_INVALID("CONFIG.TSA-URL-INVALID", "URL da TSA Inválida", "error", "CONFIG"),
    CONFIG_TSA_CONFIG_MISSING("CONFIG.TSA-CONFIG-MISSING", "Configuração da TSA Ausente", "error", "CONFIG"),
    CONFIG_TRUST_STORE_TYPE_INVALID("CONFIG.TRUST-STORE-TYPE-INVALID", "Tipo de Trust Store Inválido", "error", "CONFIG"),
    CONFIG_TRUST_STORE_EMPTY("CONFIG.TRUST-STORE-EMPTY", "Trust Store Vazio", "error", "CONFIG"),
    CONFIG_TRUST_STORE_REFERENCE_INVALID("CONFIG.TRUST-STORE-REFERENCE-INVALID", "Referência de Trust Store Inválida", "error", "CONFIG"),
    CONFIG_TRUST_STORE_URL_INVALID("CONFIG.TRUST-STORE-URL-INVALID", "URL de Trust Store Inválida", "error", "CONFIG"),
    CONFIG_TRUST_STORE_NOT_ICP_BRASIL("CONFIG.TRUST-STORE-NOT-ICP-BRASIL", "Certificado no Trust Store Não é ICP-Brasil", "error", "CONFIG"),
    CONFIG_UPDATE_INTERVAL_OUT_OF_RANGE("CONFIG.UPDATE-INTERVAL-OUT-OF-RANGE", "Intervalo de Atualização Fora da Faixa", "error", "CONFIG"),
    CONFIG_TSA_OID_INVALID("CONFIG.TSA-OID-INVALID", "OID da TSA Inválido", "error", "CONFIG"),
    CONFIG_MISSING_PARAMETER("CONFIG.MISSING-PARAMETER", "Parâmetro de Configuração Ausente", "error", "CONFIG"),
    CONFIG_CERT_MIN_DATE_INVALID("CONFIG.CERT-MIN-DATE-INVALID", "Data Mínima de Certificado Inválida", "error", "CONFIG"),
    CONFIG_CERT_MIN_DATE_OUT_OF_RANGE("CONFIG.CERT-MIN-DATE-OUT-OF-RANGE", "Data Mínima Fora da Faixa", "error", "CONFIG"),
    CONFIG_BUNDLE_SIZE_LIMIT_OUT_OF_RANGE("CONFIG.BUNDLE-SIZE-LIMIT-OUT-OF-RANGE", "Limite de Tamanho do Bundle Fora da Faixa", "error", "CONFIG"),
    CONFIG_BUNDLE_MEMORY_LIMIT_OUT_OF_RANGE("CONFIG.BUNDLE-MEMORY-LIMIT-OUT-OF-RANGE", "Limite de Memória do Bundle Fora da Faixa", "error", "CONFIG"),
    CONFIG_BUNDLE_TIMEOUT_OUT_OF_RANGE("CONFIG.BUNDLE-TIMEOUT-OUT-OF-RANGE", "Timeout do Bundle Fora da Faixa", "error", "CONFIG"),
    CONFIG_INVALID_TIMESTAMP_FORMAT("CONFIG.INVALID-TIMESTAMP-FORMAT", "Timestamp com formato inválido.", "error", "CONFIG"),
    TSA("TSA", "Problemas com Autoridade de Carimbo de Tempo", null, "TSA"),
    TSA_UNAVAILABLE("TSA.UNAVAILABLE", "TSA Indisponível", "error", "TSA"),
    TSA_INVALID_RESPONSE("TSA.INVALID-RESPONSE", "Resposta TSA Inválida", "error", "TSA"),
    TSA_INVALID_TOKEN("TSA.INVALID-TOKEN", "Token TSA Inválido", "error", "TSA"),
    TSA_VALIDATION_FAILED("TSA.VALIDATION-FAILED", "Validação TSA Falhou", "error", "TSA"),
    TEMPORAL("TEMPORAL", "Problemas Temporais", null, "TEMPORAL"),
    TEMPORAL_IAT_OUT_OF_CERT_PERIOD("TEMPORAL.IAT-OUT-OF-CERT-PERIOD", "IAT Fora do Período do Certificado", "error", "TEMPORAL"),
    TEMPORAL_IAT_INVALID("TEMPORAL.IAT-INVALID", "IAT Inválido", "error", "TEMPORAL"),
    TEMPORAL_TSA_TIMESTAMP_OUT_OF_BOUNDS("TEMPORAL.TSA-TIMESTAMP-OUT-OF-BOUNDS", "Timestamp TSA Fora dos Limites", "error", "TEMPORAL"),
    TEMPORAL_SIGNATURE_TOO_OLD("TEMPORAL.SIGNATURE-TOO-OLD", "Assinatura Muito Antiga", "warning", "TEMPORAL"),
    TEMPORAL_CLOCK_SKEW_DETECTED("TEMPORAL.CLOCK-SKEW-DETECTED", "Diferença de Relógio Detectada", "warning", "TEMPORAL"),
    VALIDATION("VALIDATION", "Problemas de Validação", null, "VALIDATION"),
    VALIDATION_SIGNATURE_VERIFICATION_FAILED("VALIDATION.SIGNATURE-VERIFICATION-FAILED", "Verificação Criptográfica da Assinatura Falhou", "error", "VALIDATION"),
    VALIDATION_UNSUPPORTED_ALGORITHM("VALIDATION.UNSUPPORTED-ALGORITHM", "Algoritmo Não Suportado para Validação", "error", "VALIDATION"),
    CACHE_CRITICAL_STALE("CACHE.CRITICAL-STALE", "Cache Crítico", null, null),
    CACHE_EXPIRED_UNSAFE("CACHE.EXPIRED-UNSAFE", "Cache Expirado", null, null),
    CACHE_STALE_BUT_VALID("CACHE.STALE-BUT-VALID", "Cache Desatualizado Válido", null, null),
    NETWORK_HASH_DOWNLOAD_FAILED("NETWORK.HASH-DOWNLOAD-FAILED", "Falha no Download do Hash", null, null),
    NETWORK_ZIP_DOWNLOAD_FAILED("NETWORK.ZIP-DOWNLOAD-FAILED", "Falha no Download do Zip", null, null),
    SECURITY_HASH_VALIDATION_FAILED("SECURITY.HASH-VALIDATION-FAILED", "Falha na Validação de Hash", null, null),
    STORAGE_INDEX_CREATION_FAILED("STORAGE.INDEX-CREATION-FAILED", "Falha na Criação de Índice", null, null),
    STORAGE_INDEX_VALIDATION_FAILED("STORAGE.INDEX-VALIDATION-FAILED", "Falha na Validação de Índice", "error", "VALIDATION"),
    VALIDATION_LTV_EVIDENCE_INVALID("VALIDATION.LTV-EVIDENCE-INVALID", "Evidências LTV Inconsistentes", "error", "VALIDATION"),
    VALIDATION_TIMESTAMP_STRATEGY_INVALID("VALIDATION.TIMESTAMP-STRATEGY-INVALID", "Estratégia de Timestamp Inválida", "error", "VALIDATION"),
    VALIDATION_POLICY_COMPLIANCE_FAILED("VALIDATION.POLICY-COMPLIANCE-FAILED", "Conformidade com Política Falhou", "error", "VALIDATION"),
    VALIDATION_SUCCESS("VALIDATION.SUCCESS", "Validação Bem-sucedida", "information", "VALIDATION"),
    SYSTEM("SYSTEM", "Problemas de Sistema", null, "SYSTEM"),
    SYSTEM_MEMORY_EXHAUSTED("SYSTEM.MEMORY-EXHAUSTED", "Memória Esgotada", "fatal", "SYSTEM"),
    SYSTEM_TIMEOUT("SYSTEM.TIMEOUT", "Timeout da Operação", "error", "SYSTEM"),
    SYSTEM_INCOMPATIBLE_LIBRARY_VERSION("SYSTEM.INCOMPATIBLE-LIBRARY-VERSION", "Versão de Biblioteca Incompatível", "warning", "SYSTEM"),
    SECURITY("SECURITY", "Problemas de Segurança", null, "SECURITY"),
    SECURITY_SIGNATURE_VALIDATION_REPLAY("SECURITY.SIGNATURE-VALIDATION-REPLAY", "Possível Ataque de Replay Detectado", "warning", "SECURITY"),
    SECURITY_BUNDLE_SIZE_LIMIT_EXCEEDED("SECURITY.BUNDLE-SIZE-LIMIT-EXCEEDED", "Limite de Tamanho do Bundle Excedido", "error", "SECURITY"),
    SECURITY_BUNDLE_MEMORY_LIMIT_EXCEEDED("SECURITY.BUNDLE-MEMORY-LIMIT-EXCEEDED", "Limite de Memória do Bundle Excedido", "error", "SECURITY"),
    SECURITY_BUNDLE_TIMEOUT_EXCEEDED("SECURITY.BUNDLE-TIMEOUT-EXCEEDED", "Timeout do Bundle Excedido", "error", "SECURITY"),
    SECURITY_PROVENANCE_SIZE_LIMIT_EXCEEDED("SECURITY.PROVENANCE-SIZE-LIMIT-EXCEEDED", "Limite de Tamanho do Provenance Excedido", "error", "SECURITY");

    public static final String SYSTEM_URI = "https://fhir.saude.go.gov.br/r4/seguranca/CodeSystem/situacao-excepcional-assinatura";
    public static final String SYSTEM_VERSION = "0.1.2";
  
    private final String code;
    private final String display;
    private final String severity;
    private final String category;

    SignatureExceptionCode(String code, String display, String severity, String category) {
        this.code = code;
        this.display = display;
        this.severity = severity;
        this.category = category;
    }
}
